version: "3.9"

services:
  db:
    image: postgres:16
    container_name: todo-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: OliverL17
      POSTGRES_DB: todo
    ports:
      - "5434:5432"
    volumes:
      - todo-data:/var/lib/postgresql/data

volumes:
  todo-data: